version: '3'

services:
  rss-bot:
    build: .
    container_name: telegram-rss-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_FILE=/app/data/rss_bot.db
      - LOG_DIR=/app/logs 