version: '3'

services:
  rss-bot:
    build: .
    container_name: telegram-rss-bot
    restart: always
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DB_FILE=/app/data/rss_bot.db
      - LOG_DIR=/app/logs 